export const SELECT_MAKE = "SELECT_MAKE";
export const SELECT_MODEL = "SELECT_MODEL";

export const POPULATE_FEATURE = "POPULATE_FEATURE"; 
export const POPULATE_MAKES = "POPULATE_MAKES"; 
export const POPULATE_MODELS = "POPULATE_MODELS"; 